import {DEPTHS} from "../../ui/depths";

export const ENEMY_TYPES = {

    1: {texture: 'enemy1', exhaust: 2, depth: DEPTHS.ENEMY},
    2: {texture: 'enemy2', exhaust: 2, depth: DEPTHS.ENEMY},
    3: {texture: 'enemy3', exhaust: 2, depth: DEPTHS.ENEMY},
    4: {texture: 'enemy4', exhaust: 2, depth: DEPTHS.ENEMY},
    5: {texture: 'enemy5', exhaust: 2, depth: DEPTHS.ENEMY},
    6: {texture: 'enemy6', exhaust: 2, depth: DEPTHS.ENEMY},
    7: {texture: 'enemy7', exhaust: 2, depth: DEPTHS.ENEMY},
    8: {texture: 'enemy8', exhaust: 2, depth: DEPTHS.ENEMY},
    9: {texture: 'enemy9', exhaust: 2, depth: DEPTHS.ENEMY},
    10: {texture: 'enemy10', exhaust: 2, depth: DEPTHS.ENEMY},
    11: {texture: 'enemy11', exhaust: 2, depth: DEPTHS.ENEMY},
    12: {texture: 'enemy12', exhaust: 2, depth: DEPTHS.ENEMY},
    13: {texture: 'enemy13', exhaust: 2, depth: DEPTHS.ENEMY},
    14: {texture: 'enemy14', exhaust: 2, depth: DEPTHS.ENEMY},
    15: {texture: 'enemy15', exhaust: 2, depth: DEPTHS.ENEMY},
    16: {texture: 'enemy16', exhaust: 2, depth: DEPTHS.ENEMY},
    17: {texture: 'enemy17', exhaust: 2, depth: DEPTHS.ENEMY},
    18: {texture: 'enemy18', exhaust: 2, depth: DEPTHS.ENEMY},
    19: {texture: 'enemy19', exhaust: 2, depth: DEPTHS.ENEMY},
    20: {texture: 'enemy20', exhaust: 2, depth: DEPTHS.ENEMY},
    21: {texture: 'enemy21', exhaust: 2, depth: DEPTHS.ENEMY},
    22: {texture: 'enemy22', exhaust: 2, depth: DEPTHS.ENEMY},
    23: {texture: 'enemy23', exhaust: 2, depth: DEPTHS.ENEMY},
    24: {texture: 'enemy24', exhaust: 2, depth: DEPTHS.ENEMY},
    25: {texture: 'enemy25', exhaust: 2, depth: DEPTHS.ENEMY},
    26: {texture: 'enemy26', exhaust: 2, depth: DEPTHS.ENEMY},
    27: {texture: 'enemy27', exhaust: 2, depth: DEPTHS.ENEMY},
    28: {texture: 'enemy28', exhaust: 2, depth: DEPTHS.ENEMY},
    29: {texture: 'enemy29', exhaust: 2, depth: DEPTHS.ENEMY},
    30: {texture: 'enemy30', exhaust: 2, depth: DEPTHS.ENEMY},
    31: {texture: 'enemy31', exhaust: 2, depth: DEPTHS.ENEMY},
    32: {texture: 'enemy32', exhaust: 2, depth: DEPTHS.ENEMY},
    33: {texture: 'enemy33', exhaust: 2, depth: DEPTHS.ENEMY},
    34: {texture: 'enemy34', exhaust: 2, depth: DEPTHS.ENEMY},
    35: {texture: 'enemy35', exhaust: 2, depth: DEPTHS.ENEMY},
    36: {texture: 'enemy36', exhaust: 2, depth: DEPTHS.ENEMY},
    37: {texture: 'enemy37', exhaust: 2, depth: DEPTHS.ENEMY},
    38: {texture: 'enemy38', exhaust: 2, depth: DEPTHS.ENEMY},
    39: {texture: 'enemy39', exhaust: 2, depth: DEPTHS.ENEMY},
    40: {texture: 'enemy40', exhaust: 2, depth: DEPTHS.ENEMY},
    41: {texture: 'enemy38', exhaust: 2, depth: DEPTHS.ENEMY},
    42: {texture: 'enemy39', exhaust: 2, depth: DEPTHS.ENEMY},
    43: {texture: 'turret1', exhaust: null, depth: DEPTHS.ENEMY_TURRET},
    44: {texture: 'turret2', exhaust: null, depth: DEPTHS.ENEMY_TURRET},
    101: {
        texture: ['meteorite1', 'meteorite2', 'meteorite3'],
        exhaust: null,
        skipSpawnEffect: true,
        depth: DEPTHS.ENEMY_METEORITE
    },

    10100: {texture: ['body1', 'body2'], exhaust: null, skipSpawnEffect: true, depth: DEPTHS.ENEMY},
    10001: {texture: 'enemy1', exhaust: 2, depth: DEPTHS.ENEMY},
    10002: {texture: 'enemy16', exhaust: 2, depth: DEPTHS.ENEMY},
    10003: {texture: 'mine1', exhaust: null, skipSpawnEffect: true, depth: DEPTHS.ENEMY_MINES},

    1001: {texture: 'enemy1', exhaust: 2, depth: DEPTHS.ENEMY_BOSS},
    1002: {texture: 'enemy2', exhaust: 2, depth: DEPTHS.ENEMY_BOSS},
    1003: {texture: 'enemy3', exhaust: 2, depth: DEPTHS.ENEMY_BOSS},
    1004: {texture: 'enemy4', exhaust: 2, depth: DEPTHS.ENEMY_BOSS},
    1005: {texture: 'enemy5', exhaust: 2, depth: DEPTHS.ENEMY_BOSS},
    1006: {texture: 'enemy6', exhaust: 2, depth: DEPTHS.ENEMY_BOSS},
    1007: {texture: 'enemy6', exhaust: 2, depth: DEPTHS.ENEMY_BOSS}
};