export const DEPTHS = {

    BACKGROUND_SKY: -10,
    BACKGROUND_CLOUDS: -9,
    BACKGROUND_STARS: -8,
    BACKGROUND_STONES: -7,
    BACKGROUND_PLANETS: -6,
    BACKGROUND_OVERLAY: -5,

    BASE: 0,
    BASE_SHIELD: 1,

    POWERUPS: 10,
    ENEMY_TURRET: 12,
    ENEMY: 13,
    ENEMY_UI: 13,
    ENEMY_METEORITE: 19,
    ENEMY_BULLET: 21.1,
    ENEMY_BOSS: 21.5,
    PLAYER: 20,
    PLAYER_SHIELD: 21,
    PLAYER_BULLET: 22,
    ENEMY_MINES: 12.1,
    LOOT: 40,

    EFFECTS_FOREGROUND: 30,

    UI_HUD: 50,

    UI_BUTTONS: 102,

    UI_NOTIFICATIONS: 1000,
    UI_OVERLAY: 1100,
    UI_MODAL: 1200,
};